### ISSUE TITLE
Does not work with es6 anymore

### ISSUE THREAD

**Issue by thetutlage** [helios1138/node-dm#25]
es6 Classes returns an error saying `Class constructors cannot be invoked without 'new'`

**Comment by helios1138** [comment]
@thetutlage Which environment with classes are you using? Is it io.js, babel, typescript, something else?

**Comment by thetutlage** [comment]
io.js

**Comment by helios1138** [comment]
resolved in 79d1f0ae6c39d7d040e7d2b6a7719ba49db65885
